### ISSUE TITLE
WindowsのexcelでCSVを開いた際の文字化け

### ISSUE THREAD

**Issue by kotaro-kinoshita** [kotaro-kinoshita/yomitoku#48]
# 事象
- CSV出力した時のWindowsのExelで開いた時に文字化けする。

# 対応
- UTF-8のみサポートしているが、Shift-JISなど文字コードの変更をサポートする必要がある

**Comment by DDAM-workshop** [comment]
すみません、使うとしたら「PermissionError: [Errno 13] Permission denied: '/usr/sbin/weakpass_edit'」という表示が出ていて助けてください。

**Comment by kotaro-kinoshita** [comment]
@DDAM-workshop 
ごめんなさい。YomiTokuを起因とするエラーではない可能性が高いのでわからないです。
ユーザと操作しようとしているフォルダの権限や所有権限が異なるのではないでしょうか、、

**Comment by ms-smz** [comment]
Excel用のCSVはBOMを付与するようにすればUTF-8のままでも文字化けしなくなります。(encoding=utf_8_sig)
Excel以外では邪魔なのでオプションでいいと思います。

**Comment by kotaro-kinoshita** [comment]
@ms-smz 
ご意見ありがとうございます。その通りだと思います。基本的にオプションとしての限定的に付与できる形にしたいと思います。

**Comment by kotaro-kinoshita** [comment]
#69

**Comment by kotaro-kinoshita** [comment]
#69
