### ISSUE TITLE
ライセンス違反状態、および現行のライセンスには課題がある

### ISSUE THREAD

**Issue by waterfa1con** [kotaro-kinoshita/yomitoku#51]
現時点(v0.5.2)で、ライセンス上2点問題があります。

- 使用しているソースコードのライセンスに則ったライセンス表記が行われていない。 
  - 例: `src/yomitoku/postprocessor/rtdetr_postprocessor.py` は Apache License 2.0 でリリースされた https://github.com/lyuwenyu/RT-DETR から流用して使用しているが、当該ソースコードおよびプロジェクト全体に対して、Apache License 2.0に従ったライセンス表記がなされていない。
- ソースコードを含めてCC BY-NC-SA 4.0でライセンスされているため、ソース公開されているにも関わらず、他者が事実上開発に参加できない。

パブリックで再頒布している状況であるため、前者はライセンス違反状態となっていると考えられます。
Apache License 2.0のライセンス条件に則った対応を早急に行う必要があります。
なお、PyPIに公開されているバイナリについても、Apache Licenseのライセンスファイルのコピーが提供されていないため、現状のままではNGではないかと思われます。

加えて、本リポジトリ内の全てのコードが、派生成果物としてCC BY-NC-SA 4.0として公開・再頒布して良いソースコードであるか、今一度ご確認ください。

後者については、仮に他者が改良を加えた場合、現状の著作権表記上、プルリクエストが送信できない可能性がある上、派生開発(fork等)が進めば進むほど著作者の表記がどんどん増えてしまう等の課題があるのではないか、というような懸念があります。

あえて選択されているということで御存知とは思いますが、Creative Commonsはソフトウェアおよびソースコードに付与するライセンスとしてはあまり適切なライセンスではありません。 (参考: https://creativecommons.jp/faq/#a5 )
「プロプライエタリな著作物ではあるが、取り組みを公開したい」なおかつ「商用利用してほしくない or 有償としたい」のであれば、GPL等の別のライセンスとのデュアルライセンスを選択すべきと考えます。

どのような理由にせよ、自分は他者の使用に制限を設けて有償ライセンスの販売を行うのにも関わらず、自身は他者のライセンス違反を行って良い理由がありません。
日本語OCRの発展という意味で、取り組み自体は非常に素晴らしいものであると感じています。しかし上記問題が大きな課題であると感じておりますので、今一度ライセンスの取り扱いについて確認・再考ください。

※ 本Issueの内容に関し、誤りが含まれる可能性があります。詳細については、弁護士等の専門家へご相談ください。

**Comment by kotaro-kinoshita** [comment]
@waterfa1con 
ご指摘ありがとうございます。一部、ライセンスの付与にあり方に課題がある可能性があるため、弁理士等の専門家に相談の上、検討したいと思います。

私の認識は以下です。
1. Apache License 2.0はパーミッシブライセンスであり、コピーレフト型のライセンスではないため、派生物を再配布する場合にプロジェクト全体を同一ライセンスを付与する義務ない認識です。部分的にApache License 2.0 から流用した部分に関しては,著作者や変更点や元のライセンスコピーを流用したコードを含むフォルダに残す対応をしたいと思います。

2. ソースコード自体の公開は行なっていますが、開発者の意図として、OSSとして公開したものではないため、意図的に他者がソースコードの開発に参加できないようにしています。ここは開発者の運用ポリシーの問題であり、ライセンス自体にそのような条項は含まれてないので、対応する予定はありません。

3. 確かにCC BY-NC-SA 4.0はソフトウェアおよびソースコードに利用されていることが推奨されているライセンスではありませんので、再考の余地が思います。ただし、商用利用不可であることを明示するためにソースコードに付与することが禁止されている訳でもありません。GPL等の別のライセンスとのデュアルライセンスを付与する案も含め、専門家に相談の上、再度、検討したいと思います。GPL系のライセンスは派生物のソースコードの開示義務のため、非常に扱いづらいライセンスですので、おそらく採用する可能性は少ないかと思います。

**Comment by waterfa1con** [comment]
@kotaro-kinoshita 
1.については、Apache License 2.0のコードを使用する際の使用条件を再度ご確認ください。
PyPI公開のwheelが4.aに対して、および本リポジトリでソースコードを公開しているため、本リポジトリは4.c に対しても違反しています。
なお、ご認識の通り、GPLとは異なり、Apache License 2.0ソースコードを使用しても、プロジェクト全体に対して同じライセンスを適用する必要はないと私も認識しています。

```
4. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:

    a. You must give any other recipients of the Work or Derivative Works a copy of this License; and
    b. You must cause any modified files to carry prominent notices stating that You changed the files; and
    c. You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
    d. If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.

You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.
```

3.については、他者による商用禁止を行うことを目的としているのに、ソースコードに対して使うには適切でないCCライセンスで、あえてソースコードをパブリックに公開する意図が私には伝わっていないだけです。

追記:
ソースコードを公開しつつ他者の商用利用を禁じて別途商用ライセンスを行うのであれば、例えばAGPLとのデュアルライセンスが考えられます。AIモデルのYOLOv8/YOLO11がそのようなライセンス形態です。
( https://www.ultralytics.com/ja/license )
そのあたりに知見が乏しいようであれば、Apache Licenseへの対応後、改めて、法務関係者にライセンス形態をご相談することをお勧めします。
