### ISSUE TITLE
縦書きのOCR layerは横書きになってしまうのが正常ですか？

### ISSUE THREAD

**Issue by oushiei120** [kotaro-kinoshita/yomitoku#52]
<img width="666" alt="image" src="https://github.com/user-attachments/assets/7a50f21e-0d8a-4b8b-949f-f9abc6cc0a02">

I noticed that the OCR layer in the image was originally supposed to be vertical, but it now appears to be horizontal. Could you please confirm if this is normal, or if something went wrong during the process?

Looking forward to your response. Thank you!

**Comment by kotaro-kinoshita** [comment]
@oushiei120 
Text rendering is handled using Pillow. For vertical text rendering within Pillow, it appears to depend on the libraqm library (https://github.com/HOST-Oman/libraqm). On Linux, this library seems to be integrated into Pillow upon installation. However, on macOS and Windows, it seems you need to install it separately.

For macOS, it is possible to resolve the issue by installing libraqm first and then reinstalling Pillow, as explained on the following page:
https://stackoverflow.com/questions/74608140/pillow-not-recognizing-libraqm-installation-on-mac-os

On Windows, however, my investigation into installing libraqm indicates that it is necessary to build libraqm manually. I have not yet been able to test this process myself.

**Comment by oushiei120** [comment]
ご回答ありがとうございます。助かりました。
環境変数設定に`echo $PKG_CONFIG_PATH
/opt/homebrew/opt/libraqm/lib/pkgconfig:`をいれることで正常になりました。
